### PR TITLE
Creates a basic react-intl setup

### PR DESCRIPTION
**Pull request by hermzz**
Basic structure for i18n using react-intl.

### CODE REVIEW

**Comment by RyanNoelk** [comment]
LGTM! A great start to i18n. Once you fix the merge conflicts, I'll merge it in.

**Review by RyanNoelk — APPROVED** [review]

**Comment by hermzz** [comment]
Added a script to generate locale file templates:

```bash
docker-compose run --rm node bash
./node_modules/.bin/babel-node scripts/merge-locale.js
```

I'll add some documentation at some point when I add it as a node task/script.

**Comment by RyanNoelk** [comment]
Awesome! 

I understand that you don't wanna add docs quite yet. But would you mind adding a quick note of that command you're using in the readme under dev notes. Pretty much what you have in your your comment will do. 

Thanks!

**Comment by hermzz** [comment]
Updated README!

**Review by RyanNoelk — APPROVED** [review]
LGTM

**Pull request merged**
