### PR TITLE
Feature - Grocery List

### PR DESCRIPTION
**Pull request by RyanNoelk**
This PR is a WIP.

@hermzz I have all the core features done for this. I still have a good amount of cleanup work for this, so you don't have to look thought the code (yet :P). But there is enough work done that I want your feedback on the overall flow. You can create/update/delete lists as well create/update/delete items on a list. 

To test:
- Update python requirements
- Run migrations
- npm install
- Log in
- Navigate to My Account -> Grocery List

My goal is that the UI should be simple and easy enough for anyone to use and understand. If you're not understanding anything let me know and I will try and explain/fix it.

Things still to do:
- unit tests for the API
- translations
- ~api code comments~
- react code comments
- ~drop dead code~
- ~clean up css (break it up into separate files)~
- ~add trans tags to all react components~
- ~reduce dom re-loads~
- ~reduce API calls~ 
- ~user validation on API and front-end~
- probably more things I'm not thinking of right now :)

### CODE REVIEW

**Comment by hermzz** [comment]
Just tried it out, works like a charm! Only found one minor bug: when adding/removing items the item count in the sidebar doesn't update.

As an aside, how easy would it be to change the looks of it? It's not a big deal, but it's not really in-keeping with what the rest of the site looks like.

**Comment by RyanNoelk** [comment]
It shouldn't be too hard to change the style. I'll work on it and update you when there is more.

**Comment by RyanNoelk** [comment]
@hermzz I'm feeling pretty good about the design of the UI and the functionality that theres. If you have some time feel free to take another look. If you have extra time, take a look at the code. I;m pretty done with the backend, but the frontend still needs a bit of work (not much though).

**Comment by RyanNoelk** [comment]
I'm closing this in favor of #147 since its much cleaner to follow

**Pull request closed without merging**
