### PR TITLE
had a look at the german translation

### PR DESCRIPTION
**Pull request by DJCrashdummy**
since i'm a native speaker, i had a quick look at the translation, compared it with the english original and corrected some minor things.

### CODE REVIEW

**Review by RyanNoelk — APPROVED** [review]
LGTM. Thanks for taking the time to fix this up! Though if you want to add anymore improvements, I would appreciate if you would add them to the dev branch. That's is where I add most of the new code before merging back into master.

**Comment by DJCrashdummy** [comment]
oh yes, sorry!
i certainly read the CONTRIBUTING.md but it seemed pointless to me for my first contribution (fixing a link) so i unfortunately forgot about this...

**Comment by DJCrashdummy** [comment]
btw @RyanNoelk why then not change the default branch to "dev"?

**Comment by RyanNoelk** [comment]
TBH its not super necessary for this repo but I like to follow best practice. Sometimes I'll leave bigger features in the dev branch so I can personally use it and test it while keeping master as clean as possible.

**Pull request merged**
