### PR TITLE
Spanish translation update

### PR DESCRIPTION
**Pull request by bglopez**
Updated some of the Spanish translation to remove remaining English phrases

### CODE REVIEW

**Review by RyanNoelk — APPROVED** [review]
LGTM

**Comment by RyanNoelk** [comment]
As a side note, there are going to be some more transitions that I can use a hand with. I haven't been doing a good job with keeping them up to date (mainly because I don't speak Spanish and my german isn't great). I'll create a new branch/PR with the update trans files. If you wouldn't mind giving me some help with more translations on the Spanish side, that would be great!

**Comment by bglopez** [comment]
Let me know when you've got the update translation files branched off and I'll work on the Spanish :+1:

**Comment by RyanNoelk** [comment]
Thanks for the help! You can find the PR here:  https://github.com/RyanNoelk/OpenEats/pull/254

**Pull request merged**
