### PR TITLE
Feature/add drf docs

### PR DESCRIPTION
**Pull request by lpasselin**
Adds DRF-docs to the REST api.
http://demo.drfdocs.com/

### CODE REVIEW

**Comment by lpasselin** [comment]
Seeing the docs this produces, there is something bad in some urls.py
http://i.imgur.com/G1fFcc5.jpg

It is probably related to DefaultRouter, used in list/urls.py, ingredients/urls.py, etc, which makes a root url everytime it is used.
http://www.django-rest-framework.org/api-guide/routers/#defaultrouter

Can we use SimpleRouter instead of DefaultRouter without breaking the UI? Do you need the root and .json formatting for UI?

**Comment by RyanNoelk** [comment]
The UI URLs are super easy for me to manage. I have all the API end points in a common file [here](https://github.com/RyanNoelk/OpenEats/blob/dev/frontend/modules/common/config.js). So don't worry about changing the URL structure. 

Using a SimpleRouter seems to be the best way to go. I tried it out on `ingredient` and it worked fine. There seem to be two issues though
1. The URLs aren't grouped by the app that they are associated with. Like in the demo.
2. the whole URL isn't present. In the docs, right now its says `/ingredient/`when it should be `api/v1/ingredient/ingredient/`. I would have no problem changing the URL to `api/v1/ingredient/` but we need the `api/v1/` there.

Once you get this working, we should also make the doc strings a bit better for the viewsets. Doesn't seem super helpful if the docs for those aren't good. :)

-Ryan

**Comment by lpasselin** [comment]
I'm on it.

**Comment by RyanNoelk** [comment]
BTW I also merged in my doc change branch. So you may want to sync your branch with dev.

**Comment by lpasselin** [comment]
Displaying separate app labels should be fixed soon.
https://github.com/manosim/django-rest-framework-docs/issues/144

**Comment by RyanNoelk** [comment]
That issue is a big blocker for us. Not only does it generate the wrong URLs but also doesn't allow proper grouping.

Lets hold off on this till that is resolved. We may even just fork/create our own doc page. Its a really cool idea.

**Comment by lpasselin** [comment]
I agree.

**Pull request closed without merging**
